---
title: "1_VolcanoPlot"
author: "Jaakko"
date: "2025-11-20"
format:
  html:
    css: /styles.css
    code-copy: true 
    code-line-numbers: true
    code-overflow: scroll
    code-tools: true
    highlight-style: github-dark
engine: knitr
execute:
  echo: true
  eval: true
conda:
  environment: bioinfo #bioinfo_environment.yml
---

## Quarto

This is a Quarto document. Quarto is a multi-language, next-generation version of R Markdown. Check the [tutorial](https://quarto.org/docs/get-started/hello/rstudio.html).\
N.B. - Learn the IT foundations to master bioinformatics tools and softwares, and prevent getting tangled on the infamous "dependency hell". Ask for the "Foundations of Bioinformatics Infrastructure".

**---------- DATA GENERATION (check "Data generation for plotting"**

## Download the RNA-seq dataset

Let's use a real example - [*RNA-seq of ITPR3 and RELB knockout in SW480 under normoxia and hypoxia*]{.underline} (*Homo sapiens*) <https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197576>.

## Check the data ad extract the samples of interest

## Read the data into R and make a DESeq2 object

### PCA Analysis to verify your results

**---------- PLOT**

## Make a perfect Volcano plot

What is a volcano plot? It's a SCATTER PLOT:

-   x-axis = log2FoldChange

-   y-axis = -log10(p-values)

```{r}
res %>%
  as.data.frame() %>%
  ggplot(aes(x = log2FoldChange, y = log10(pvalue))) +
  geom_point()
```

What are the points on the top?
